#!/bin/sh
set -e
# Automatically added by dh_icons
if which update-icon-caches >/dev/null 2>&1 ; then
	update-icon-caches /usr/share/icons/smoothX-Xfce /usr/share/icons/smoothX-Blue-N /usr/share/icons/smoothX-Violet /usr/share/icons/smoothX-Trans /usr/share/icons/smoothX-Red /usr/share/icons/smoothX-Butterfly
fi
# End automatically added section
#DEBHELPER#