#!/bin/sh
set -e
# Automatically added by dh_icons
if which update-icon-caches >/dev/null 2>&1 ; then
	update-icon-caches /usr/share/icons/smoothX-Xfce /usr/share/icons/smoothX-Blue-Dark /usr/share/icons/smoothX-Blue-N /usr/share/icons/smoothX-Violet /usr/share/icons/smoothX-Trans /usr/share/icons/smoothX-Red /usr/share/icons/smoothX-New-Green /usr/share/icons/smoothX-Ubuntu /usr/share/icons/smoothX-Brown-N /usr/share/icons/smoothX-Purple-N /usr/share/icons/smoothX-Leather
fi
# End automatically added section
#DEBHELPER#